import streamlit as st

st.title("ℹ️ About the Project")
st.markdown("---")
st.image("assets/Audiobook.webp")

st.write("This project, 'Audiobook Generation from eBook,' is designed to convert eBooks into audiobooks using advanced text-to-speech technology. The application provides a user-friendly interface where users can upload their eBooks in various formats, and the app processes the text to generate high-quality audio files that can be downloaded and enjoyed on the go.")
st.write("The project aims to enhance accessibility to literature, making it easier for individuals to enjoy books while multitasking or for those with visual impairments. By leveraging state-of-the-art TTS engines, the application ensures that the generated audiobooks are natural-sounding and pleasant to listen to.")
st.write("Feel free to explore the app and transform your reading experience with audiobooks!")
st.markdown("---")

st.title("📌 About the Project")
st.markdown("---")
st.write("The Audiobook Generator from eBook is a Python-based project designed to convert traditional eBooks (PDF and EPUB formats) into audiobooks using Text-to-Speech (TTS) technology.")
st.write("This application leverages libraries such as gTTS (Google Text-to-Speech) and pyttsx3 to transform written text into natural-sounding speech. Users can upload their eBooks, and the app processes the text to generate audio files in MP3 format, which can be easily downloaded and listened to on various devices.")
st.write("The project aims to enhance accessibility to literature, making it easier for individuals to enjoy books while multitasking or for those with visual impairments. By providing a simple and efficient way to convert eBooks into audiobooks, this application seeks to enrich the reading experience and promote a love for literature in a modern, convenient format.")
st.markdown("---")

st.title("📌 Features")
st.markdown("---")
st.write("1. **User-Friendly Interface**: The application features an intuitive interface built with Streamlit, allowing users to easily navigate and interact with the app.")
st.write("2. **Multiple eBook Formats**: Supports uploading eBooks in various formats, including PDF and EPUB, ensuring compatibility with a wide range of books.")
st.write("3. **High-Quality Text-to-Speech Conversion**: Utilizes advanced TTS libraries like gTTS and pyttsx3 to generate natural-sounding speech from the text content of eBooks.")
st.write("4. **Audio File Generation**: Converts the text into audio files in MP3 format, which can be easily downloaded and played on various devices.")
st.write("5. **Customizable Voice Options**: Offers options to choose different voices and speech rates, allowing users to personalize their listening experience.")
st.write("6. **Accessibility**: Enhances accessibility to literature for individuals with visual impairments or reading difficulties by providing an alternative way to consume content.")
st.markdown("---")

st.title("📌 Technologies Used")
st.markdown("---")
st.write("1. **Streamlit**: A powerful framework for building interactive web applications in Python.")
st.write("2. **Python**: The primary programming language used for developing the application.")
st.write("3. **gTTS (Google Text-to-Speech)**: A library that interfaces with Google Translate's text-to-speech API to convert text into speech.")
st.write("4. **pyttsx3**: A text-to-speech conversion library in Python that works offline and is compatible with multiple TTS engines.")
st.write("5. **PDF and EPUB Libraries**: Libraries such as PyMuPDF (fitz) and ebooklib for extracting text from PDF and EPUB files, respectively.")
st.write("6. **File Handling**: Techniques for uploading and processing eBook files in various formats.")
st.write("7. **Audio Processing**: Methods for generating and saving audio files in formats like MP3.")
st.write("8. **HTML/CSS**: For customizing the appearance of the web application.")
st.markdown("---")

st.title("📌 Objectives")
st.markdown("---")
st.write("1. **Convert eBooks to Audiobooks**: Provide a simple and efficient way for users to convert their eBooks into audiobooks using advanced text-to-speech technology.")
st.write("2. **Enhance Accessibility**: Make literature more accessible to a wider audience, including individuals with visual impairments or reading difficulties.")
st.write("3. **Improve User Experience**: Utilize high-quality TTS engines to ensure that the generated audiobooks are pleasant to listen to, enhancing the overall user experience.")
st.write("4. **Support Multiple Formats**: Allow users to upload eBooks in various formats (PDF, EPUB) to cater to different preferences and needs.")
st.write("5. **Promote Literature**: Encourage a love for reading by providing an alternative way to consume books, making it easier for people to enjoy literature in a busy lifestyle.")
st.markdown("---")

st.title("📌 User Benefits")
st.markdown("---")
st.write("1. **Convenience**: Users can listen to audiobooks while multitasking, commuting, or exercising, making it easier to enjoy books in a busy lifestyle.")
st.write("2. **Accessibility**: The app provides an alternative way to consume literature, making it accessible to individuals with visual impairments or reading difficulties.")
st.write("3. **Personalization**: Users can customize their listening experience by choosing different voices and speech rates.")
st.write("4. **Wide Compatibility**: The generated audiobooks are in MP3 format, which can be played on various devices, including smartphones, tablets, and computers.")
st.write("5. **Cost-Effective**: The application is free to use, allowing users to convert their eBooks into audiobooks without any additional cost.")    
st.markdown("---")

st.title("📌 Conclusion")
st.markdown("---")
st.write("The Audiobook Generator from eBook project successfully addresses the need for accessible and convenient ways to enjoy literature. By leveraging advanced text-to-speech technology, the application provides users with a simple and efficient method to convert their eBooks into high-quality audiobooks.")
st.write("The app's user-friendly interface, support for multiple eBook formats, and customizable voice options enhance the overall user experience, making it easy for individuals to access and enjoy their favorite books in audio format. This project not only promotes a love for reading but also ensures that literature is accessible to a wider audience, including those with visual impairments or busy lifestyles.")
st.write("Overall, the Audiobook Generator from eBook project represents a significant step towards making literature more accessible and enjoyable for everyone.")
st.markdown("---")

st.title("📌 Acknowledgment")
st.markdown("---")
st.write("I would like to express my sincere gratitude to everyone who has contributed to the successful completion of the 'Audiobook Generation from eBook' project. This project would not have been possible without the support and guidance of several individuals and resources.")
st.write("First and foremost, I would like to thank my mentors and instructors for their invaluable guidance and encouragement throughout the development of this project. Their expertise and insights have been instrumental in shaping the direction and quality of the application.")
st.write("I would also like to acknowledge the open-source community for providing the libraries and tools that made this project feasible. The developers of Streamlit, gTTS, pyttsx3, and other libraries have created powerful resources that enabled me to implement the core functionalities of the app.")
st.write("Finally, I am grateful to my friends and family for their unwavering support and motivation during the course of this project. Their encouragement has been a constant source of inspiration.")
st.markdown("---")

st.markdown("<h2 style='text-align: center'>📚Happy Listening!📚</h2>", unsafe_allow_html=True)
st.markdown("---")

st.markdown("<h3 style='text-align: center'>Books speak, and now you can listen.</h3>", unsafe_allow_html=True)
st.markdown("<h3 style='text-align: center'>Start your journey today 🎧</h3>", unsafe_allow_html=True)
st.markdown("---")

# button for navigation
st.markdown("<h3 style='text-align: center'>👇CLICK BELOW👇</h3>", unsafe_allow_html=True)
# st.button("About", key="about", on_click=lambda: st.experimental_set_query_params(page="about"))
# st.markdown("---")
if st.button("Go to Audio Page"):
    st.switch_page("pages/audio.py")
